config/routes.rb
Rails.application.routes.draw do
  resources :comments do
    member do 
      post 'upvote'
    end
  end

  resources :artworks

  root 'artworks#index'
  

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :artwork
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
    @comment = Comment.new
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: 'Artwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:title, :style, :location, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @comment = Comment.find(params[:id])
    @comment.votes.create
    redirect_to :back
  end

  # def downvote
  #   @comment = Comment.find(params[:id])
  #   @comment.votes.last.destroy
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:textbox, :artwork_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artworks/_form.html.erb
<%= form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Artist" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>


  <div class="actions">            
    <div class="text-right"> <%= f.submit class: 'btn btn-default' %></div>
</div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing Artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index2.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artworks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Style</th>
      <th>Location</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artworks.each do |artwork| %>
      <tr>
        <td><%= artwork.title %></td>
        <td><%= artwork.style %></td>
        <td><%= artwork.location %></td>
        <td><%= artwork.description %></td>
        <td><%= link_to 'Show', artwork %></td>
        <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
        <td><%= link_to 'Destroy', artwork_path(artwork), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artwork', new_artwork_path %>

app/views/artworks/new.html.erb
<h1>New Artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DIVE DEEP</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/shop-item.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style>
     #map {
       width: 400px;
       height: 300px;
     }
   </style>
   <script src="https://maps.googleapis.com/maps/api/js"></script>
   <script>
     function initialize() {
       var mapCanvas = document.getElementById('map');
       var mapOptions = {
         center: new google.maps.LatLng(25.801160, -80.199968),
         zoom: 16,
         mapTypeId: google.maps.MapTypeId.ROADMAP
       }
       var map = new google.maps.Map(mapCanvas, mapOptions)

       var locations = [];
         locations.push ( {name:"Kazki 1", latlng: new google.maps.LatLng(25.801199, -80.200104)})
         

       for(var i=0;i<locations.length;i++ ) {
           var marker = new google.maps.Marker({position: locations[i].latlng,map:map, title:locations[i].name});

       }

       // var point = new google.maps.LatLng(25.801579, -80.202176);

     


       // var marker = new google.maps.Marker({
       //     position:point,
       //     map:map,
       // })

       var contentstring = '<div> Sup</div>';
       var infowindow = new google.maps.InfoWindow({
           content:contentstring
       })

       google.maps.event.addListener(marker,'click',function(){

         infowindow.open(map,marker);


       });
}

     

     google.maps.event.addDomListener(window, 'load', initialize);
   </script>
   
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                </button>
                <a class="navbar-brand" href=""><h3 style= "font-family: Futura"><%= link_to 'Back', artworks_path %></h3></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        
                    </li>
                    <li>
                        
                    </li>
                    <li>
                        
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
    <div class="container">

        <div class="row">

            <div class="col-md-12">

                <div class="thumbnail" style="padding: 50px padding-bottom: 25px padding-top: 500px">
                  <%= image_tag(@artwork.location, class: "img-responsive") %>
<br>
                      <p>
  <strong>Artist:</strong>
  <%= @artwork.title %>
</p>

<p>
  <strong>Website:</strong>
  <%= @artwork.style %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artwork.description %>
</p>

<p>
  <h3><strong><center>Location</center></strong></h3>
<center><div id="map"></div</center>
</p>
                    </div> 
                </div>
                <div class="well">
                  <h3 class="yay">

<h3>New Comment</h3>

<%= render 'comments/form' %>

     <hr>

<h3>Comments:</h3>


<% @artwork.comments.each do |comment| %>
<p>
  <%= comment.textbox %> 
  (Added: <em><%= time_ago_in_words(comment.created_at) %> ago</em>)
<%= button_to 'like me!', upvote_comment_path(comment), method: :post %>  <%= pluralize(comment.votes.count, "vote") %>
</p>
<hr>
<% end %>

                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Miguel Salazar 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

<%#= link_to 'Edit', edit_artwork_path(@artwork) %> |

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="text-align: left">
    <%= f.label "  " %>
    <%= f.text_area :textbox %>
  </div>

  <% if @artwork.nil? %>
  <div class="field">
    <%= f.label :artwork_id %>
    <%= f.text_field :artwork_id %>
  </div>
  <% else %>
    <%= f.hidden_field :artwork_id, value: @artwork.id %>
    <% end %>

  <div class="actions" style="text-align: left">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Textbox</th>
      <th>Artwork</th>
      <th>Comment Count</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.textbox %></td>
        <td><%= comment.artwork %></td>
        <td><%= pluralize(comment.votes.count, "vote") %><%= button_to 'like', upvote_comment_path(comment), method: :post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Here is your comment!:</strong>
  <%= @comment.textbox %>
</p>

<p>
  <strong>Artwork:</strong>
  <%= @comment.artwork %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> | <% if @comment.artwork.nil? %>
<%= link_to 'Back', comments_path %>
<% else %>
<%= link_to 'Back', @comment.artwork %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WYNC</title>
  <link rel="image_src" href="/images/wynwood" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Raleway+Dots' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
     #map {
       width: 1,350px;
       height: 500px;
     }
   </style>
   <script src="https://maps.googleapis.com/maps/api/js"></script>
   <script>
     function initialize() {
       var mapCanvas = document.getElementById('map');
       var mapOptions = {
         center: new google.maps.LatLng(25.801160, -80.199968),
         zoom: 16,
         mapTypeId: google.maps.MapTypeId.ROADMAP
       }
       var map = new google.maps.Map(mapCanvas, mapOptions)

       var locations = [];
         locations.push ( {name:"Kazki 1", latlng: new google.maps.LatLng(25.801199, -80.200104)})
         locations.push ( {name:"Kazki 2", latlng: new google.maps.LatLng(25.801439, -80.199953)})
         locations.push ( {name:"Kazki 3", latlng: new google.maps.LatLng(25.801607, -80.201799)})
         locations.push ( {name:"Kashink", latlng: new google.maps.LatLng(25.801516, -80.201640)})
         locations.push ( {name:"El Mac", latlng: new google.maps.LatLng(25.802260, -80.205127)})
         locations.push ( {name:"Banksy", latlng: new google.maps.LatLng(25.801275, -80.199570)})

       for(var i=0;i<locations.length;i++ ) {
           var marker = new google.maps.Marker({position: locations[i].latlng,map:map, title:locations[i].name});

       }

       // var point = new google.maps.LatLng(25.801579, -80.202176);




       // var marker = new google.maps.Marker({
       //     position:point,
       //     map:map,
       // })

       var contentstring = '<div> Sup</div>';
       var infowindow = new google.maps.InfoWindow({
           content:contentstring
       })

       google.maps.event.addListener(marker,'click',function(){

         infowindow.open(map,marker);


       });
}



     google.maps.event.addDomListener(window, 'load', initialize);
   </script>


</head>
<body id="page-top" class="index">

<%= yield %>

</body>
</html>